#!/bin/sh -l
#QSUB -queue F4cpu
#QSUB -node 1
#PBS -l walltime=1:00:00
#PBS -N gen_struc
cd $PBS_O_WORKDIR


EXE='/your_home/.pyenv/versions/miniconda3-4.3.30/bin/python3.6'
$EXE -u /path_to/cryspy.py 1>> log  2>> err

