#!/bin/sh -l
#QSUB -queue F4cpu
#QSUB -node 1
#PBS -l walltime=2:00:00
#PBS -N sistruc
cd $PBS_O_WORKDIR
module unload mpt/2.14
module load intel-mpi/5.1.3.258


EXE='/home/k0362/k036200/.pyenv/versions/miniconda2-4.1.11/bin/python2.7'


$EXE /home/k0362/k036200/CSPY/0.2.0/cspy.py >> log 

