#!/bin/sh -l
#QSUB -queue F4cpu
#QSUB -node 1
#QSUB -mpi 24
#QSUB -omp 1
#PBS -l walltime=2:00:00
#PBS -N Si_cspyID
cd $PBS_O_WORKDIR
module unload mpt/2.14
module load intel-mpi/5.1.3.258

EXEPATH='/home/k0362/k036200/QE/qe-6.1/bin'
EXE='pw.x'

echo "--------------------------------"
echo ""
echo "Running $EXEPATH/$EXE ..."
date
echo ""
echo "--------------------------------"


mpijob ${EXEPATH}/$EXE -npool 8 < pwscf.in > pwscf.out

echo "--------------------------------"
echo ""
echo "done!"
date
echo ""
echo "--------------------------------"

sed -i -e '3d' stat_job
echo 'done' >> stat_job
