#!/bin/sh -l
#QSUB -queue F4cpu
#QSUB -node 1
#QSUB -mpi 24
#QSUB -omp 1
#PBS -l walltime=6:00:00
#PBS -N SicspyID
cd $PBS_O_WORKDIR
module unload mpt/2.14
module load intel-mpi/5.1.3.258

EXEPATH='/home/k0362/k036200/VASP/vasp.5.4.1/bin'
EXE='vasp_std'
#EXE='vasp_gam'
#EXE='vasp_ncl'

echo "--------------------------------"
echo ""
echo "Running $EXEPATH/$EXE ..."
date
echo ""
echo "--------------------------------"

rm -f STOPCAR

mpijob ${EXEPATH}/$EXE > stdout.log

echo "--------------------------------"
echo ""
echo "done!"
date
echo ""
echo "--------------------------------"

sed -i -e '3d' stat_job
echo 'done' >> stat_job
